zuul:
  routes:
    worm-service:
      path: /wormService/**
      serviceId: worm-service
    novel-service:
      path: /novelService1/**
      serviceId: novel-service
    file-service:
      path: /fileService/**
      serviceId: file-service
  prefix: /service
